#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_WEB_GYM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WiBuGym")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    partial void InsertThuTrongTuan(ThuTrongTuan instance);
    partial void UpdateThuTrongTuan(ThuTrongTuan instance);
    partial void DeleteThuTrongTuan(ThuTrongTuan instance);
    partial void InsertThoiGian(ThoiGian instance);
    partial void UpdateThoiGian(ThoiGian instance);
    partial void DeleteThoiGian(ThoiGian instance);
    partial void InsertTenLoaiTinTuc(TenLoaiTinTuc instance);
    partial void UpdateTenLoaiTinTuc(TenLoaiTinTuc instance);
    partial void DeleteTenLoaiTinTuc(TenLoaiTinTuc instance);
    partial void InsertTaiKhoanKH(TaiKhoanKH instance);
    partial void UpdateTaiKhoanKH(TaiKhoanKH instance);
    partial void DeleteTaiKhoanKH(TaiKhoanKH instance);
    partial void InsertPT(PT instance);
    partial void UpdatePT(PT instance);
    partial void DeletePT(PT instance);
    partial void InsertKhoaTap(KhoaTap instance);
    partial void UpdateKhoaTap(KhoaTap instance);
    partial void DeleteKhoaTap(KhoaTap instance);
    partial void InsertDangKyKhoaTap(DangKyKhoaTap instance);
    partial void UpdateDangKyKhoaTap(DangKyKhoaTap instance);
    partial void DeleteDangKyKhoaTap(DangKyKhoaTap instance);
    partial void InsertCLB(CLB instance);
    partial void UpdateCLB(CLB instance);
    partial void DeleteCLB(CLB instance);
    partial void InsertChiTietDangKyKhoaTap(ChiTietDangKyKhoaTap instance);
    partial void UpdateChiTietDangKyKhoaTap(ChiTietDangKyKhoaTap instance);
    partial void DeleteChiTietDangKyKhoaTap(ChiTietDangKyKhoaTap instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WiBuGymConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<ThuTrongTuan> ThuTrongTuans
		{
			get
			{
				return this.GetTable<ThuTrongTuan>();
			}
		}
		
		public System.Data.Linq.Table<ThoiGian> ThoiGians
		{
			get
			{
				return this.GetTable<ThoiGian>();
			}
		}
		
		public System.Data.Linq.Table<TenLoaiTinTuc> TenLoaiTinTucs
		{
			get
			{
				return this.GetTable<TenLoaiTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanQTV> TaiKhoanQTVs
		{
			get
			{
				return this.GetTable<TaiKhoanQTV>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanKH> TaiKhoanKHs
		{
			get
			{
				return this.GetTable<TaiKhoanKH>();
			}
		}
		
		public System.Data.Linq.Table<PT> PTs
		{
			get
			{
				return this.GetTable<PT>();
			}
		}
		
		public System.Data.Linq.Table<KhoaTap> KhoaTaps
		{
			get
			{
				return this.GetTable<KhoaTap>();
			}
		}
		
		public System.Data.Linq.Table<DangKyKhoaTap> DangKyKhoaTaps
		{
			get
			{
				return this.GetTable<DangKyKhoaTap>();
			}
		}
		
		public System.Data.Linq.Table<CLB> CLBs
		{
			get
			{
				return this.GetTable<CLB>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDangKyKhoaTap> ChiTietDangKyKhoaTaps
		{
			get
			{
				return this.GetTable<ChiTietDangKyKhoaTap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idType;
		
		private string _Title;
		
		private string _description;
		
		private string _urlImg;
		
		private System.Nullable<int> _idNewsType;
		
		private EntityRef<TenLoaiTinTuc> _TenLoaiTinTuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTypeChanging(int value);
    partial void OnidTypeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnurlImgChanging(string value);
    partial void OnurlImgChanged();
    partial void OnidNewsTypeChanging(System.Nullable<int> value);
    partial void OnidNewsTypeChanged();
    #endregion
		
		public TinTuc()
		{
			this._TenLoaiTinTuc = default(EntityRef<TenLoaiTinTuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idType", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idType
		{
			get
			{
				return this._idType;
			}
			set
			{
				if ((this._idType != value))
				{
					this.OnidTypeChanging(value);
					this.SendPropertyChanging();
					this._idType = value;
					this.SendPropertyChanged("idType");
					this.OnidTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImg", DbType="VarChar(128)")]
		public string urlImg
		{
			get
			{
				return this._urlImg;
			}
			set
			{
				if ((this._urlImg != value))
				{
					this.OnurlImgChanging(value);
					this.SendPropertyChanging();
					this._urlImg = value;
					this.SendPropertyChanged("urlImg");
					this.OnurlImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNewsType", DbType="Int")]
		public System.Nullable<int> idNewsType
		{
			get
			{
				return this._idNewsType;
			}
			set
			{
				if ((this._idNewsType != value))
				{
					if (this._TenLoaiTinTuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNewsTypeChanging(value);
					this.SendPropertyChanging();
					this._idNewsType = value;
					this.SendPropertyChanged("idNewsType");
					this.OnidNewsTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TenLoaiTinTuc_TinTuc", Storage="_TenLoaiTinTuc", ThisKey="idNewsType", OtherKey="idNewsType", IsForeignKey=true)]
		public TenLoaiTinTuc TenLoaiTinTuc
		{
			get
			{
				return this._TenLoaiTinTuc.Entity;
			}
			set
			{
				TenLoaiTinTuc previousValue = this._TenLoaiTinTuc.Entity;
				if (((previousValue != value) 
							|| (this._TenLoaiTinTuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TenLoaiTinTuc.Entity = null;
						previousValue.TinTucs.Remove(this);
					}
					this._TenLoaiTinTuc.Entity = value;
					if ((value != null))
					{
						value.TinTucs.Add(this);
						this._idNewsType = value.idNewsType;
					}
					else
					{
						this._idNewsType = default(Nullable<int>);
					}
					this.SendPropertyChanged("TenLoaiTinTuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuTrongTuan")]
	public partial class ThuTrongTuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDOW;
		
		private string _dateInWeek;
		
		private EntitySet<KhoaTap> _KhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDOWChanging(int value);
    partial void OnidDOWChanged();
    partial void OndateInWeekChanging(string value);
    partial void OndateInWeekChanged();
    #endregion
		
		public ThuTrongTuan()
		{
			this._KhoaTaps = new EntitySet<KhoaTap>(new Action<KhoaTap>(this.attach_KhoaTaps), new Action<KhoaTap>(this.detach_KhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDOW", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDOW
		{
			get
			{
				return this._idDOW;
			}
			set
			{
				if ((this._idDOW != value))
				{
					this.OnidDOWChanging(value);
					this.SendPropertyChanging();
					this._idDOW = value;
					this.SendPropertyChanged("idDOW");
					this.OnidDOWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInWeek", DbType="NVarChar(50)")]
		public string dateInWeek
		{
			get
			{
				return this._dateInWeek;
			}
			set
			{
				if ((this._dateInWeek != value))
				{
					this.OndateInWeekChanging(value);
					this.SendPropertyChanging();
					this._dateInWeek = value;
					this.SendPropertyChanged("dateInWeek");
					this.OndateInWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuTrongTuan_KhoaTap", Storage="_KhoaTaps", ThisKey="idDOW", OtherKey="idDOW")]
		public EntitySet<KhoaTap> KhoaTaps
		{
			get
			{
				return this._KhoaTaps;
			}
			set
			{
				this._KhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.ThuTrongTuan = this;
		}
		
		private void detach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.ThuTrongTuan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThoiGian")]
	public partial class ThoiGian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTime;
		
		private System.Nullable<System.TimeSpan> _timeStart;
		
		private System.Nullable<System.TimeSpan> _timeEnd;
		
		private string _timeStartEnd;
		
		private EntitySet<KhoaTap> _KhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTimeChanging(int value);
    partial void OnidTimeChanged();
    partial void OntimeStartChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeStartChanged();
    partial void OntimeEndChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeEndChanged();
    partial void OntimeStartEndChanging(string value);
    partial void OntimeStartEndChanged();
    #endregion
		
		public ThoiGian()
		{
			this._KhoaTaps = new EntitySet<KhoaTap>(new Action<KhoaTap>(this.attach_KhoaTaps), new Action<KhoaTap>(this.detach_KhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTime", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTime
		{
			get
			{
				return this._idTime;
			}
			set
			{
				if ((this._idTime != value))
				{
					this.OnidTimeChanging(value);
					this.SendPropertyChanging();
					this._idTime = value;
					this.SendPropertyChanged("idTime");
					this.OnidTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> timeStart
		{
			get
			{
				return this._timeStart;
			}
			set
			{
				if ((this._timeStart != value))
				{
					this.OntimeStartChanging(value);
					this.SendPropertyChanging();
					this._timeStart = value;
					this.SendPropertyChanged("timeStart");
					this.OntimeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> timeEnd
		{
			get
			{
				return this._timeEnd;
			}
			set
			{
				if ((this._timeEnd != value))
				{
					this.OntimeEndChanging(value);
					this.SendPropertyChanging();
					this._timeEnd = value;
					this.SendPropertyChanged("timeEnd");
					this.OntimeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeStartEnd", DbType="VarChar(50)")]
		public string timeStartEnd
		{
			get
			{
				return this._timeStartEnd;
			}
			set
			{
				if ((this._timeStartEnd != value))
				{
					this.OntimeStartEndChanging(value);
					this.SendPropertyChanging();
					this._timeStartEnd = value;
					this.SendPropertyChanged("timeStartEnd");
					this.OntimeStartEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiGian_KhoaTap", Storage="_KhoaTaps", ThisKey="idTime", OtherKey="idTime")]
		public EntitySet<KhoaTap> KhoaTaps
		{
			get
			{
				return this._KhoaTaps;
			}
			set
			{
				this._KhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.ThoiGian = this;
		}
		
		private void detach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.ThoiGian = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TenLoaiTinTuc")]
	public partial class TenLoaiTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idNewsType;
		
		private string _newsTypeName;
		
		private EntitySet<TinTuc> _TinTucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNewsTypeChanging(int value);
    partial void OnidNewsTypeChanged();
    partial void OnnewsTypeNameChanging(string value);
    partial void OnnewsTypeNameChanged();
    #endregion
		
		public TenLoaiTinTuc()
		{
			this._TinTucs = new EntitySet<TinTuc>(new Action<TinTuc>(this.attach_TinTucs), new Action<TinTuc>(this.detach_TinTucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNewsType", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idNewsType
		{
			get
			{
				return this._idNewsType;
			}
			set
			{
				if ((this._idNewsType != value))
				{
					this.OnidNewsTypeChanging(value);
					this.SendPropertyChanging();
					this._idNewsType = value;
					this.SendPropertyChanged("idNewsType");
					this.OnidNewsTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newsTypeName", DbType="NVarChar(50)")]
		public string newsTypeName
		{
			get
			{
				return this._newsTypeName;
			}
			set
			{
				if ((this._newsTypeName != value))
				{
					this.OnnewsTypeNameChanging(value);
					this.SendPropertyChanging();
					this._newsTypeName = value;
					this.SendPropertyChanged("newsTypeName");
					this.OnnewsTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TenLoaiTinTuc_TinTuc", Storage="_TinTucs", ThisKey="idNewsType", OtherKey="idNewsType")]
		public EntitySet<TinTuc> TinTucs
		{
			get
			{
				return this._TinTucs;
			}
			set
			{
				this._TinTucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.TenLoaiTinTuc = this;
		}
		
		private void detach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.TenLoaiTinTuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanQTV")]
	public partial class TaiKhoanQTV
	{
		
		private int _IDTaiKhoan;
		
		private string _Account;
		
		private string _Password;
		
		public TaiKhoanQTV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this._IDTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanKH")]
	public partial class TaiKhoanKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGuest;
		
		private string _accountKH;
		
		private string _passwordKH;
		
		private string _fullName;
		
		private string _phoneNumber;
		
		private System.Nullable<bool> _gender;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gmail;
		
		private EntitySet<DangKyKhoaTap> _DangKyKhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGuestChanging(int value);
    partial void OnidGuestChanged();
    partial void OnaccountKHChanging(string value);
    partial void OnaccountKHChanged();
    partial void OnpasswordKHChanging(string value);
    partial void OnpasswordKHChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OngenderChanging(System.Nullable<bool> value);
    partial void OngenderChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OngmailChanging(string value);
    partial void OngmailChanged();
    #endregion
		
		public TaiKhoanKH()
		{
			this._DangKyKhoaTaps = new EntitySet<DangKyKhoaTap>(new Action<DangKyKhoaTap>(this.attach_DangKyKhoaTaps), new Action<DangKyKhoaTap>(this.detach_DangKyKhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuest", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idGuest
		{
			get
			{
				return this._idGuest;
			}
			set
			{
				if ((this._idGuest != value))
				{
					this.OnidGuestChanging(value);
					this.SendPropertyChanging();
					this._idGuest = value;
					this.SendPropertyChanged("idGuest");
					this.OnidGuestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountKH", DbType="VarChar(50)")]
		public string accountKH
		{
			get
			{
				return this._accountKH;
			}
			set
			{
				if ((this._accountKH != value))
				{
					this.OnaccountKHChanging(value);
					this.SendPropertyChanging();
					this._accountKH = value;
					this.SendPropertyChanged("accountKH");
					this.OnaccountKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwordKH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string passwordKH
		{
			get
			{
				return this._passwordKH;
			}
			set
			{
				if ((this._passwordKH != value))
				{
					this.OnpasswordKHChanging(value);
					this.SendPropertyChanging();
					this._passwordKH = value;
					this.SendPropertyChanged("passwordKH");
					this.OnpasswordKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(50)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this.OngmailChanging(value);
					this.SendPropertyChanging();
					this._gmail = value;
					this.SendPropertyChanged("gmail");
					this.OngmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKH_DangKyKhoaTap", Storage="_DangKyKhoaTaps", ThisKey="idGuest", OtherKey="idGuest")]
		public EntitySet<DangKyKhoaTap> DangKyKhoaTaps
		{
			get
			{
				return this._DangKyKhoaTaps;
			}
			set
			{
				this._DangKyKhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKH = this;
		}
		
		private void detach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PT")]
	public partial class PT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPT;
		
		private string _namePT;
		
		private string _phoneNumber;
		
		private string _gmail;
		
		private string _urlImage;
		
		private EntitySet<KhoaTap> _KhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPTChanging(int value);
    partial void OnidPTChanged();
    partial void OnnamePTChanging(string value);
    partial void OnnamePTChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OngmailChanging(string value);
    partial void OngmailChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    #endregion
		
		public PT()
		{
			this._KhoaTaps = new EntitySet<KhoaTap>(new Action<KhoaTap>(this.attach_KhoaTaps), new Action<KhoaTap>(this.detach_KhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPT
		{
			get
			{
				return this._idPT;
			}
			set
			{
				if ((this._idPT != value))
				{
					this.OnidPTChanging(value);
					this.SendPropertyChanging();
					this._idPT = value;
					this.SendPropertyChanged("idPT");
					this.OnidPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namePT", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string namePT
		{
			get
			{
				return this._namePT;
			}
			set
			{
				if ((this._namePT != value))
				{
					this.OnnamePTChanging(value);
					this.SendPropertyChanging();
					this._namePT = value;
					this.SendPropertyChanged("namePT");
					this.OnnamePTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(100)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this.OngmailChanging(value);
					this.SendPropertyChanging();
					this._gmail = value;
					this.SendPropertyChanged("gmail");
					this.OngmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(128)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PT_KhoaTap", Storage="_KhoaTaps", ThisKey="idPT", OtherKey="idPT")]
		public EntitySet<KhoaTap> KhoaTaps
		{
			get
			{
				return this._KhoaTaps;
			}
			set
			{
				this._KhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.PT = this;
		}
		
		private void detach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.PT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoaTap")]
	public partial class KhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCourse;
		
		private string _nameCourse;
		
		private System.Nullable<System.DateTime> _startDay;
		
		private System.Nullable<System.DateTime> _dueDay;
		
		private System.Nullable<int> _price;
		
		private string _descriptionKT;
		
		private string _urlImg;
		
		private System.Nullable<int> _idCLB;
		
		private System.Nullable<int> _idTime;
		
		private System.Nullable<int> _idDOW;
		
		private System.Nullable<int> _idPT;
		
		private EntitySet<ChiTietDangKyKhoaTap> _ChiTietDangKyKhoaTaps;
		
		private EntityRef<PT> _PT;
		
		private EntityRef<ThoiGian> _ThoiGian;
		
		private EntityRef<ThuTrongTuan> _ThuTrongTuan;
		
		private EntityRef<CLB> _CLB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCourseChanging(int value);
    partial void OnidCourseChanged();
    partial void OnnameCourseChanging(string value);
    partial void OnnameCourseChanged();
    partial void OnstartDayChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDayChanged();
    partial void OndueDayChanging(System.Nullable<System.DateTime> value);
    partial void OndueDayChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OndescriptionKTChanging(string value);
    partial void OndescriptionKTChanged();
    partial void OnurlImgChanging(string value);
    partial void OnurlImgChanged();
    partial void OnidCLBChanging(System.Nullable<int> value);
    partial void OnidCLBChanged();
    partial void OnidTimeChanging(System.Nullable<int> value);
    partial void OnidTimeChanged();
    partial void OnidDOWChanging(System.Nullable<int> value);
    partial void OnidDOWChanged();
    partial void OnidPTChanging(System.Nullable<int> value);
    partial void OnidPTChanged();
    #endregion
		
		public KhoaTap()
		{
			this._ChiTietDangKyKhoaTaps = new EntitySet<ChiTietDangKyKhoaTap>(new Action<ChiTietDangKyKhoaTap>(this.attach_ChiTietDangKyKhoaTaps), new Action<ChiTietDangKyKhoaTap>(this.detach_ChiTietDangKyKhoaTaps));
			this._PT = default(EntityRef<PT>);
			this._ThoiGian = default(EntityRef<ThoiGian>);
			this._ThuTrongTuan = default(EntityRef<ThuTrongTuan>);
			this._CLB = default(EntityRef<CLB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCourse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCourse
		{
			get
			{
				return this._idCourse;
			}
			set
			{
				if ((this._idCourse != value))
				{
					this.OnidCourseChanging(value);
					this.SendPropertyChanging();
					this._idCourse = value;
					this.SendPropertyChanged("idCourse");
					this.OnidCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameCourse", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string nameCourse
		{
			get
			{
				return this._nameCourse;
			}
			set
			{
				if ((this._nameCourse != value))
				{
					this.OnnameCourseChanging(value);
					this.SendPropertyChanging();
					this._nameCourse = value;
					this.SendPropertyChanged("nameCourse");
					this.OnnameCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDay", DbType="Date")]
		public System.Nullable<System.DateTime> startDay
		{
			get
			{
				return this._startDay;
			}
			set
			{
				if ((this._startDay != value))
				{
					this.OnstartDayChanging(value);
					this.SendPropertyChanging();
					this._startDay = value;
					this.SendPropertyChanged("startDay");
					this.OnstartDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dueDay", DbType="Date")]
		public System.Nullable<System.DateTime> dueDay
		{
			get
			{
				return this._dueDay;
			}
			set
			{
				if ((this._dueDay != value))
				{
					this.OndueDayChanging(value);
					this.SendPropertyChanging();
					this._dueDay = value;
					this.SendPropertyChanged("dueDay");
					this.OndueDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionKT", DbType="NVarChar(1000)")]
		public string descriptionKT
		{
			get
			{
				return this._descriptionKT;
			}
			set
			{
				if ((this._descriptionKT != value))
				{
					this.OndescriptionKTChanging(value);
					this.SendPropertyChanging();
					this._descriptionKT = value;
					this.SendPropertyChanged("descriptionKT");
					this.OndescriptionKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImg", DbType="VarChar(128)")]
		public string urlImg
		{
			get
			{
				return this._urlImg;
			}
			set
			{
				if ((this._urlImg != value))
				{
					this.OnurlImgChanging(value);
					this.SendPropertyChanging();
					this._urlImg = value;
					this.SendPropertyChanged("urlImg");
					this.OnurlImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCLB", DbType="Int")]
		public System.Nullable<int> idCLB
		{
			get
			{
				return this._idCLB;
			}
			set
			{
				if ((this._idCLB != value))
				{
					if (this._CLB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCLBChanging(value);
					this.SendPropertyChanging();
					this._idCLB = value;
					this.SendPropertyChanged("idCLB");
					this.OnidCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTime", DbType="Int")]
		public System.Nullable<int> idTime
		{
			get
			{
				return this._idTime;
			}
			set
			{
				if ((this._idTime != value))
				{
					if (this._ThoiGian.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTimeChanging(value);
					this.SendPropertyChanging();
					this._idTime = value;
					this.SendPropertyChanged("idTime");
					this.OnidTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDOW", DbType="Int")]
		public System.Nullable<int> idDOW
		{
			get
			{
				return this._idDOW;
			}
			set
			{
				if ((this._idDOW != value))
				{
					if (this._ThuTrongTuan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDOWChanging(value);
					this.SendPropertyChanging();
					this._idDOW = value;
					this.SendPropertyChanged("idDOW");
					this.OnidDOWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPT", DbType="Int")]
		public System.Nullable<int> idPT
		{
			get
			{
				return this._idPT;
			}
			set
			{
				if ((this._idPT != value))
				{
					if (this._PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPTChanging(value);
					this.SendPropertyChanging();
					this._idPT = value;
					this.SendPropertyChanged("idPT");
					this.OnidPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaTap_ChiTietDangKyKhoaTap", Storage="_ChiTietDangKyKhoaTaps", ThisKey="idCourse", OtherKey="idCourse")]
		public EntitySet<ChiTietDangKyKhoaTap> ChiTietDangKyKhoaTaps
		{
			get
			{
				return this._ChiTietDangKyKhoaTaps;
			}
			set
			{
				this._ChiTietDangKyKhoaTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PT_KhoaTap", Storage="_PT", ThisKey="idPT", OtherKey="idPT", IsForeignKey=true)]
		public PT PT
		{
			get
			{
				return this._PT.Entity;
			}
			set
			{
				PT previousValue = this._PT.Entity;
				if (((previousValue != value) 
							|| (this._PT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PT.Entity = null;
						previousValue.KhoaTaps.Remove(this);
					}
					this._PT.Entity = value;
					if ((value != null))
					{
						value.KhoaTaps.Add(this);
						this._idPT = value.idPT;
					}
					else
					{
						this._idPT = default(Nullable<int>);
					}
					this.SendPropertyChanged("PT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiGian_KhoaTap", Storage="_ThoiGian", ThisKey="idTime", OtherKey="idTime", IsForeignKey=true)]
		public ThoiGian ThoiGian
		{
			get
			{
				return this._ThoiGian.Entity;
			}
			set
			{
				ThoiGian previousValue = this._ThoiGian.Entity;
				if (((previousValue != value) 
							|| (this._ThoiGian.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThoiGian.Entity = null;
						previousValue.KhoaTaps.Remove(this);
					}
					this._ThoiGian.Entity = value;
					if ((value != null))
					{
						value.KhoaTaps.Add(this);
						this._idTime = value.idTime;
					}
					else
					{
						this._idTime = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThoiGian");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuTrongTuan_KhoaTap", Storage="_ThuTrongTuan", ThisKey="idDOW", OtherKey="idDOW", IsForeignKey=true)]
		public ThuTrongTuan ThuTrongTuan
		{
			get
			{
				return this._ThuTrongTuan.Entity;
			}
			set
			{
				ThuTrongTuan previousValue = this._ThuTrongTuan.Entity;
				if (((previousValue != value) 
							|| (this._ThuTrongTuan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuTrongTuan.Entity = null;
						previousValue.KhoaTaps.Remove(this);
					}
					this._ThuTrongTuan.Entity = value;
					if ((value != null))
					{
						value.KhoaTaps.Add(this);
						this._idDOW = value.idDOW;
					}
					else
					{
						this._idDOW = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThuTrongTuan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLB_KhoaTap", Storage="_CLB", ThisKey="idCLB", OtherKey="idCLB", IsForeignKey=true)]
		public CLB CLB
		{
			get
			{
				return this._CLB.Entity;
			}
			set
			{
				CLB previousValue = this._CLB.Entity;
				if (((previousValue != value) 
							|| (this._CLB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLB.Entity = null;
						previousValue.KhoaTaps.Remove(this);
					}
					this._CLB.Entity = value;
					if ((value != null))
					{
						value.KhoaTaps.Add(this);
						this._idCLB = value.idCLB;
					}
					else
					{
						this._idCLB = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDangKyKhoaTaps(ChiTietDangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.KhoaTap = this;
		}
		
		private void detach_ChiTietDangKyKhoaTaps(ChiTietDangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.KhoaTap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyKhoaTap")]
	public partial class DangKyKhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idInvoice;
		
		private int _idGuest;
		
		private System.Nullable<System.DateTime> _idDate;
		
		private System.Nullable<bool> _status;
		
		private EntitySet<ChiTietDangKyKhoaTap> _ChiTietDangKyKhoaTaps;
		
		private EntityRef<TaiKhoanKH> _TaiKhoanKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidInvoiceChanging(int value);
    partial void OnidInvoiceChanged();
    partial void OnidGuestChanging(int value);
    partial void OnidGuestChanged();
    partial void OnidDateChanging(System.Nullable<System.DateTime> value);
    partial void OnidDateChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public DangKyKhoaTap()
		{
			this._ChiTietDangKyKhoaTaps = new EntitySet<ChiTietDangKyKhoaTap>(new Action<ChiTietDangKyKhoaTap>(this.attach_ChiTietDangKyKhoaTaps), new Action<ChiTietDangKyKhoaTap>(this.detach_ChiTietDangKyKhoaTaps));
			this._TaiKhoanKH = default(EntityRef<TaiKhoanKH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInvoice", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idInvoice
		{
			get
			{
				return this._idInvoice;
			}
			set
			{
				if ((this._idInvoice != value))
				{
					this.OnidInvoiceChanging(value);
					this.SendPropertyChanging();
					this._idInvoice = value;
					this.SendPropertyChanged("idInvoice");
					this.OnidInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuest", DbType="Int NOT NULL")]
		public int idGuest
		{
			get
			{
				return this._idGuest;
			}
			set
			{
				if ((this._idGuest != value))
				{
					if (this._TaiKhoanKH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidGuestChanging(value);
					this.SendPropertyChanging();
					this._idGuest = value;
					this.SendPropertyChanged("idGuest");
					this.OnidGuestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> idDate
		{
			get
			{
				return this._idDate;
			}
			set
			{
				if ((this._idDate != value))
				{
					this.OnidDateChanging(value);
					this.SendPropertyChanging();
					this._idDate = value;
					this.SendPropertyChanged("idDate");
					this.OnidDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKyKhoaTap_ChiTietDangKyKhoaTap", Storage="_ChiTietDangKyKhoaTaps", ThisKey="idInvoice", OtherKey="idInvoice")]
		public EntitySet<ChiTietDangKyKhoaTap> ChiTietDangKyKhoaTaps
		{
			get
			{
				return this._ChiTietDangKyKhoaTaps;
			}
			set
			{
				this._ChiTietDangKyKhoaTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKH_DangKyKhoaTap", Storage="_TaiKhoanKH", ThisKey="idGuest", OtherKey="idGuest", IsForeignKey=true)]
		public TaiKhoanKH TaiKhoanKH
		{
			get
			{
				return this._TaiKhoanKH.Entity;
			}
			set
			{
				TaiKhoanKH previousValue = this._TaiKhoanKH.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoanKH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoanKH.Entity = null;
						previousValue.DangKyKhoaTaps.Remove(this);
					}
					this._TaiKhoanKH.Entity = value;
					if ((value != null))
					{
						value.DangKyKhoaTaps.Add(this);
						this._idGuest = value.idGuest;
					}
					else
					{
						this._idGuest = default(int);
					}
					this.SendPropertyChanged("TaiKhoanKH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDangKyKhoaTaps(ChiTietDangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.DangKyKhoaTap = this;
		}
		
		private void detach_ChiTietDangKyKhoaTaps(ChiTietDangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.DangKyKhoaTap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLB")]
	public partial class CLB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCLB;
		
		private string _CLBName;
		
		private string _addressCLB;
		
		private string _urlImg;
		
		private string _phoneNumber;
		
		private EntitySet<KhoaTap> _KhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCLBChanging(int value);
    partial void OnidCLBChanged();
    partial void OnCLBNameChanging(string value);
    partial void OnCLBNameChanged();
    partial void OnaddressCLBChanging(string value);
    partial void OnaddressCLBChanged();
    partial void OnurlImgChanging(string value);
    partial void OnurlImgChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    #endregion
		
		public CLB()
		{
			this._KhoaTaps = new EntitySet<KhoaTap>(new Action<KhoaTap>(this.attach_KhoaTaps), new Action<KhoaTap>(this.detach_KhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCLB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCLB
		{
			get
			{
				return this._idCLB;
			}
			set
			{
				if ((this._idCLB != value))
				{
					this.OnidCLBChanging(value);
					this.SendPropertyChanging();
					this._idCLB = value;
					this.SendPropertyChanged("idCLB");
					this.OnidCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLBName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string CLBName
		{
			get
			{
				return this._CLBName;
			}
			set
			{
				if ((this._CLBName != value))
				{
					this.OnCLBNameChanging(value);
					this.SendPropertyChanging();
					this._CLBName = value;
					this.SendPropertyChanged("CLBName");
					this.OnCLBNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressCLB", DbType="NVarChar(128)")]
		public string addressCLB
		{
			get
			{
				return this._addressCLB;
			}
			set
			{
				if ((this._addressCLB != value))
				{
					this.OnaddressCLBChanging(value);
					this.SendPropertyChanging();
					this._addressCLB = value;
					this.SendPropertyChanged("addressCLB");
					this.OnaddressCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImg", DbType="VarChar(128)")]
		public string urlImg
		{
			get
			{
				return this._urlImg;
			}
			set
			{
				if ((this._urlImg != value))
				{
					this.OnurlImgChanging(value);
					this.SendPropertyChanging();
					this._urlImg = value;
					this.SendPropertyChanged("urlImg");
					this.OnurlImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLB_KhoaTap", Storage="_KhoaTaps", ThisKey="idCLB", OtherKey="idCLB")]
		public EntitySet<KhoaTap> KhoaTaps
		{
			get
			{
				return this._KhoaTaps;
			}
			set
			{
				this._KhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.CLB = this;
		}
		
		private void detach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.CLB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDangKyKhoaTap")]
	public partial class ChiTietDangKyKhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idInvoice;
		
		private int _idCourse;
		
		private System.Nullable<int> _price;
		
		private EntityRef<DangKyKhoaTap> _DangKyKhoaTap;
		
		private EntityRef<KhoaTap> _KhoaTap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidInvoiceChanging(int value);
    partial void OnidInvoiceChanged();
    partial void OnidCourseChanging(int value);
    partial void OnidCourseChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public ChiTietDangKyKhoaTap()
		{
			this._DangKyKhoaTap = default(EntityRef<DangKyKhoaTap>);
			this._KhoaTap = default(EntityRef<KhoaTap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInvoice", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idInvoice
		{
			get
			{
				return this._idInvoice;
			}
			set
			{
				if ((this._idInvoice != value))
				{
					if (this._DangKyKhoaTap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidInvoiceChanging(value);
					this.SendPropertyChanging();
					this._idInvoice = value;
					this.SendPropertyChanged("idInvoice");
					this.OnidInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCourse", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCourse
		{
			get
			{
				return this._idCourse;
			}
			set
			{
				if ((this._idCourse != value))
				{
					if (this._KhoaTap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCourseChanging(value);
					this.SendPropertyChanging();
					this._idCourse = value;
					this.SendPropertyChanged("idCourse");
					this.OnidCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKyKhoaTap_ChiTietDangKyKhoaTap", Storage="_DangKyKhoaTap", ThisKey="idInvoice", OtherKey="idInvoice", IsForeignKey=true)]
		public DangKyKhoaTap DangKyKhoaTap
		{
			get
			{
				return this._DangKyKhoaTap.Entity;
			}
			set
			{
				DangKyKhoaTap previousValue = this._DangKyKhoaTap.Entity;
				if (((previousValue != value) 
							|| (this._DangKyKhoaTap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DangKyKhoaTap.Entity = null;
						previousValue.ChiTietDangKyKhoaTaps.Remove(this);
					}
					this._DangKyKhoaTap.Entity = value;
					if ((value != null))
					{
						value.ChiTietDangKyKhoaTaps.Add(this);
						this._idInvoice = value.idInvoice;
					}
					else
					{
						this._idInvoice = default(int);
					}
					this.SendPropertyChanged("DangKyKhoaTap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaTap_ChiTietDangKyKhoaTap", Storage="_KhoaTap", ThisKey="idCourse", OtherKey="idCourse", IsForeignKey=true)]
		public KhoaTap KhoaTap
		{
			get
			{
				return this._KhoaTap.Entity;
			}
			set
			{
				KhoaTap previousValue = this._KhoaTap.Entity;
				if (((previousValue != value) 
							|| (this._KhoaTap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaTap.Entity = null;
						previousValue.ChiTietDangKyKhoaTaps.Remove(this);
					}
					this._KhoaTap.Entity = value;
					if ((value != null))
					{
						value.ChiTietDangKyKhoaTaps.Add(this);
						this._idCourse = value.idCourse;
					}
					else
					{
						this._idCourse = default(int);
					}
					this.SendPropertyChanged("KhoaTap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
